[build]
  # Build command for the frontend
  command = "cd frontend && npm install && npm run build"
  # Directory to publish
  publish = "frontend/out"
  # Base directory
  base = "/"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Enable Next.js runtime
  NEXT_RUNTIME = "edge"

# Frontend build settings
[[build.processing]]
  skip_processing = false

[[build.processing.css]]
  bundle = true
  minify = true

[[build.processing.js]]
  bundle = true
  minify = true

# Redirects for SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (will be set in Netlify dashboard)
[context.production.environment]
  NEXT_PUBLIC_API_BASE_URL = "https://your-api-url.com"
  NEXT_PUBLIC_WS_URL = "wss://your-websocket-url.com"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_BASE_URL = "https://f1-analytics-api-staging.herokuapp.com"
  NEXT_PUBLIC_WS_URL = "wss://f1-analytics-ws-staging.herokuapp.com"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 